//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyConsoleApplication.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.DataTransferSoap")]
    public interface DataTransferSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckVersion(string stdCodeJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckVersionAsync(string stdCodeJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUserList(string stdCodeJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUserListAsync(string stdCodeJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrtlResStatusList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPrtlResStatusList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrtlResStatusList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPrtlResStatusListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUseLineList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUseLineList(string use_line_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUseLineList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUseLineListAsync(string use_line_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPtrlPlanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPtrlPlanList(string jsonParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPtrlPlanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPtrlPlanListAsync(string jsonParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastPtrlResList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLastPtrlResList(string jsonParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastPtrlResList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetLastPtrlResListAsync(string jsonParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhoneNumberList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPhoneNumberList(string jsonParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhoneNumberList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPhoneNumberListAsync(string jsonParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemDateTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSystemDateTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemDateTime", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSystemDateTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetLinePtrlResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SetLinePtrlResult(string jsonEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetLinePtrlResult", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SetLinePtrlResultAsync(string jsonEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPtrlPointRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SetPtrlPointRecord(string jsonEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPtrlPointRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SetPtrlPointRecordAsync(string jsonEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPtrlContenRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SetPtrlContenRecord(string jsonEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPtrlContenRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SetPtrlContenRecordAsync(string jsonEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPtrlUnit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SetPtrlUnit(string jsonEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPtrlUnit", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SetPtrlUnitAsync(string jsonEntity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataTransferSoapChannel : DailyConsoleApplication.ServiceReference1.DataTransferSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataTransferSoapClient : System.ServiceModel.ClientBase<DailyConsoleApplication.ServiceReference1.DataTransferSoap>, DailyConsoleApplication.ServiceReference1.DataTransferSoap {
        
        public DataTransferSoapClient() {
        }
        
        public DataTransferSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataTransferSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataTransferSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataTransferSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckVersion(string stdCodeJson) {
            return base.Channel.CheckVersion(stdCodeJson);
        }
        
        public System.Threading.Tasks.Task<string> CheckVersionAsync(string stdCodeJson) {
            return base.Channel.CheckVersionAsync(stdCodeJson);
        }
        
        public string GetUserList(string stdCodeJson) {
            return base.Channel.GetUserList(stdCodeJson);
        }
        
        public System.Threading.Tasks.Task<string> GetUserListAsync(string stdCodeJson) {
            return base.Channel.GetUserListAsync(stdCodeJson);
        }
        
        public string GetPrtlResStatusList() {
            return base.Channel.GetPrtlResStatusList();
        }
        
        public System.Threading.Tasks.Task<string> GetPrtlResStatusListAsync() {
            return base.Channel.GetPrtlResStatusListAsync();
        }
        
        public string GetUseLineList(string use_line_id) {
            return base.Channel.GetUseLineList(use_line_id);
        }
        
        public System.Threading.Tasks.Task<string> GetUseLineListAsync(string use_line_id) {
            return base.Channel.GetUseLineListAsync(use_line_id);
        }
        
        public string GetPtrlPlanList(string jsonParams) {
            return base.Channel.GetPtrlPlanList(jsonParams);
        }
        
        public System.Threading.Tasks.Task<string> GetPtrlPlanListAsync(string jsonParams) {
            return base.Channel.GetPtrlPlanListAsync(jsonParams);
        }
        
        public string GetLastPtrlResList(string jsonParams) {
            return base.Channel.GetLastPtrlResList(jsonParams);
        }
        
        public System.Threading.Tasks.Task<string> GetLastPtrlResListAsync(string jsonParams) {
            return base.Channel.GetLastPtrlResListAsync(jsonParams);
        }
        
        public string GetPhoneNumberList(string jsonParams) {
            return base.Channel.GetPhoneNumberList(jsonParams);
        }
        
        public System.Threading.Tasks.Task<string> GetPhoneNumberListAsync(string jsonParams) {
            return base.Channel.GetPhoneNumberListAsync(jsonParams);
        }
        
        public string GetSystemDateTime() {
            return base.Channel.GetSystemDateTime();
        }
        
        public System.Threading.Tasks.Task<string> GetSystemDateTimeAsync() {
            return base.Channel.GetSystemDateTimeAsync();
        }
        
        public string SetLinePtrlResult(string jsonEntity) {
            return base.Channel.SetLinePtrlResult(jsonEntity);
        }
        
        public System.Threading.Tasks.Task<string> SetLinePtrlResultAsync(string jsonEntity) {
            return base.Channel.SetLinePtrlResultAsync(jsonEntity);
        }
        
        public string SetPtrlPointRecord(string jsonEntity) {
            return base.Channel.SetPtrlPointRecord(jsonEntity);
        }
        
        public System.Threading.Tasks.Task<string> SetPtrlPointRecordAsync(string jsonEntity) {
            return base.Channel.SetPtrlPointRecordAsync(jsonEntity);
        }
        
        public string SetPtrlContenRecord(string jsonEntity) {
            return base.Channel.SetPtrlContenRecord(jsonEntity);
        }
        
        public System.Threading.Tasks.Task<string> SetPtrlContenRecordAsync(string jsonEntity) {
            return base.Channel.SetPtrlContenRecordAsync(jsonEntity);
        }
        
        public string SetPtrlUnit(string jsonEntity) {
            return base.Channel.SetPtrlUnit(jsonEntity);
        }
        
        public System.Threading.Tasks.Task<string> SetPtrlUnitAsync(string jsonEntity) {
            return base.Channel.SetPtrlUnitAsync(jsonEntity);
        }
    }
}
